export const WORK_HISTORY = [
  {
    company: 'Machinarium',
    role: 'Senior Full-Stack Developer',
    isContract: true,
    isRemote: true,
    country: 'Turkey',
    website: 'https://machinarium.co/',
    descriptions: [
      'More than 4 projects development completed.',
      'UI bugs and performance issues fixed for websites.',
      'With React Native, a mobile app structure is implemented. UI components and API connections were developed.',
      'Backend structure implemented with Nest.js and development completed.',
    ],
    stacks:
      'React, React Native, Next.js, EcmaScript6, Typescript, HTML/SCSS, Nest.js, Mysql, Node.js, Redux Toolkit(RTK Query), Websocket',
    start: 'Feb 2022',
    end: 'Feb 2023',
  },
  {
    company: 'Mintus',
    role: 'Senior Front-End Developer',
    isContract: true,
    isRemote: false,
    country: 'Turkey',
    website: 'https://www.mintus.com/',
    descriptions: [
      'Website and dashboard rebuilt with new design and Next.js in less than 2 months.',
      'UI bugs and performance issues were fixed.',
      '3rd Party marketing and analytics integrations implemented, such as Google Analytics, GTM, Heap.io',
    ],
    stacks: 'Next.js, React, EcmaScript6, Redux Toolkit, Websocket, HTML/SCSS',
    start: 'Sep 2021',
    end: 'Feb 2022',
  },
  {
    company: 'Bilyoner.com',
    role: 'Senior Front-End Developer',
    isContract: true,
    isRemote: true,
    country: 'Turkey',
    website: 'https://www.bilyoner.com/',
    descriptions: [
      '3rd Party marketing and analytics integrations implemented, such as Google Analytics, GTM, MixPanel and etc.',
      'UI bugs and performance issues fixed for desktop and mobile web.',
    ],
    stacks: 'EcmaScript6, React, Redux, Websocket, HTML/SCSS',
    start: 'Dec 2020',
    end: 'Feb 2021',
  },
  {
    company: 'Ziylan Group',
    role: 'Senior Front-End Developer',
    isContract: true,
    isRemote: false,
    country: 'Turkey',
    website: 'https://www.flo.com.tr/',
    descriptions: [
      'More than 4 projects development completed.',
      '3rd Party marketing and analytics integrations implemented, such as Google Analytics, GTM',
      'UI bugs and performance issues fixed for desktop and mobile web.',
    ],
    stacks: 'jQuery, EcmaScript6, HTML/SCSS',
    start: 'Apr 2019',
    end: 'Feb 2021',
  },
  {
    company: 'Alegra',
    role: 'Senior Front-End Developer',
    isContract: false,
    isRemote: false,
    country: 'Turkey',
    website: 'http://alegra.io/',
    descriptions: [
      '3rd Party analytics integrations implemented, such as Google Analytics, GTM',
      'More than 5 e-commerce projects development completed.',
      'Single page application was developed without a library.',
    ],
    stacks: 'jQuery, EcmaScript6, HTML/SCSS, AMP, Node.js',
    start: 'Jul 2015',
    end: 'Apr 2019',
  },
  {
    company: 'Efabrika',
    role: 'Front-End Developer',
    isContract: false,
    isRemote: false,
    country: 'Turkey',
    website: 'https://efabrika.com/',
    descriptions: [
      'More than 5 projects development completed.',
      'UI designs implemented for web projects',
      'Mobile apps were developed with PhoneGap',
    ],
    stacks: 'jQuery, PhoneGap, HTML/SCSS, Node.js, Javascript, PHP',
    start: 'Dec 2012',
    end: 'Jul 2015',
  },
];

export const SKILLS = [
  'React',
  'React Native',
  'Javascript (ES6)',
  'TypeScript',
  'Node.js',
  'Next.js',
  'Tailwind CSS',
  'Nest.js',
  'Redux (RTK Query)',
  'WebSocket',
];

export const CLIENTS: Record<string, { order: number; className?: string }> = {
  mintus: { order: 1 },
  boyner: { order: 2 },
  bilyoner: { order: 3 },
  flo: { order: 4 },
  turkishairlines: { order: 5 },
  millitakimlar: { order: 6, className: 'grayscale' },
  minted: { order: 7 },
  clickmelive: { order: 8 },
  colendi: { order: 9 },
  procat: { order: 10 },
  hangikredi: { order: 11 },
  withbeyond: { order: 12 },
  cactushotels: { order: 13 },
  instreet: { order: 14 },
  lumberjack: { order: 15 },
  nadirgold: { order: 16 },
  ninewest: { order: 17 },
  pinaronline: { order: 18 },
};
