export const WORK_HISTORY = [
  {
    company: 'Machinarium',
    role: 'Senior Full-Stack Developer',
    isContract: true,
    isRemote: true,
    country: 'Turkey',
    descriptions: [
      'More than 4 projects development completed.',
      'UI bugs and performance issues fixed for websites.',
      'With React Native, mobile app structure implemented. UI components and API connections was developed.',
      'Backend structure implemented with Nest.js and development completed.',
    ],
    stacks:
      'React, React Native, Next.js, EcmaScript6, Typescript, HTML/SCSS, Nest.js, Mysql, Node.js, Redux Toolkit(RTK Query), Websocket',
    start: 'Feb 2022',
    end: 'Feb 2023',
  },
  {
    company: 'Mintus',
    role: 'Senior Front-End Developer',
    isContract: true,
    isRemote: false,
    country: 'Turkey',
    descriptions: [
      'Website and dashboard rebuilt with new design and Next.js in less than 2 months.',
      'UI bugs and performance issues fixed.',
      '3rd Party marketing and analytics integrations implemented, such as Google Analytics, GTM, Heap.io',
    ],
    stacks: 'Next.js, React, EcmaScript6, Redux Toolkit, Websocket, HTML/SCSS',
    start: 'Sep 2021',
    end: 'Feb 2022',
  },
  {
    company: 'Bilyoner.com',
    role: 'Senior Front-End Developer',
    isContract: true,
    isRemote: true,
    country: 'Turkey',
    descriptions: [
      '3rd Party marketing and analytics integrations implemented, such as Google Analytics, GTM, MixPanel and etc.',
      'UI bugs and performance issues fixed for desktop and mobile web.',
    ],
    stacks: 'EcmaScript6, React, Redux, Websocket, HTML/SCSS',
    start: 'Dec 2020',
    end: 'Feb 2021',
  },
  {
    company: 'Ziylan Group',
    role: 'Senior Front-End Developer',
    isContract: true,
    isRemote: false,
    country: 'Turkey',
    descriptions: [
      'More than 4 projects development completed.',
      '3rd Party marketing and analytics integrations implemented, such as Google Analytics, GTM',
      'UI bugs and performance issues fixed for desktop and mobile web.',
    ],
    stacks: 'jQuery, EcmaScript6, HTML/SCSS',
    start: 'Apr 2019',
    end: 'Feb 2021',
  },
  {
    company: 'Alegra',
    role: 'Senior Front-End Developer',
    isContract: false,
    isRemote: false,
    country: 'Turkey',
    descriptions: [
      '3rd Party analytics integrations implemented, such as Google Analytics, GTM',
      'More than 5 ecommerce projects development completed.',
      'Single page application was developed without library.',
    ],
    stacks: 'jQuery, EcmaScript6, HTML/SCSS, AMP, Node.js',
    start: 'Jul 2015',
    end: 'Apr 2019',
  },
  {
    company: 'Efabrika',
    role: 'Front-End Developer',
    isContract: false,
    isRemote: false,
    country: 'Turkey',
    descriptions: [
      'More than 5 projects development completed.',
      'UI designs implemented for web projects',
      'Mobile apps was developed with PhoneGap',
    ],
    stacks: 'jQuery, PhoneGap, HTML/SCSS, Node.js, Javascript, PHP',
    start: 'Dec 2012',
    end: 'Jul 2015',
  },
];

export const SKILLS = [
  'React',
  'React Native',
  'Javascript (ES6)',
  'TypeScript',
  'Node.js',
  'Next.js',
  'Tailwind CSS',
  'Nest.js',
  'Redux (RTK Query)',
  'WebSocket',
];
